"""Corpus + MCP-token service layer.

A corpus is a thematic grouping of public collections; an MCP token
grants programmatic read access scoped to a corpus. The platform's
only consumer today is the MCP server plugin (see
``app/plugins/mcp_server/``).

The plaintext token is generated by ``secrets.token_urlsafe(32)``
and bcrypt-hashed before persistence — only ``hashed_token`` lives
in the DB. ``resolve_token`` walks every non-revoked row of the
matching corpus to find a hash that verifies, then bumps
``last_used_at`` so admins can spot stale tokens at a glance.
"""

from __future__ import annotations

import secrets
import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.exceptions import (
    DomainValidationError,
    NotFoundError,
)
from app.core.password import hash_password, verify_password
from app.models.collection import Collection
from app.models.corpus import Corpus, McpToken, corpus_collections
from app.models.user import User


# ── Corpus CRUD ───────────────────────────────────────────────────────────────


async def list_corpora(db: AsyncSession) -> list[tuple[Corpus, int]]:
    """Return every corpus + the count of non-revoked tokens it owns.

    The token count comes from a single COUNT subquery rather than an
    eager-loaded relationship because tokens are admin-only data —
    most callers (the admin list page) want the count, not the rows.
    """
    from sqlalchemy import func

    rows = (
        await db.execute(
            select(Corpus)
            .options(selectinload(Corpus.collections))
            .order_by(Corpus.name.asc())
        )
    ).scalars().all()
    out: list[tuple[Corpus, int]] = []
    for c in rows:
        active = await db.scalar(
            select(func.count(McpToken.id))
            .where(McpToken.corpus_id == c.id)
            .where(McpToken.revoked_at.is_(None))
        )
        out.append((c, int(active or 0)))
    return out


async def get_corpus(db: AsyncSession, corpus_id: uuid.UUID) -> tuple[Corpus, int]:
    """Fetch a corpus + its non-revoked token count, or raise NotFoundError."""
    from sqlalchemy import func

    corpus = await db.scalar(
        select(Corpus)
        .where(Corpus.id == corpus_id)
        .options(selectinload(Corpus.collections))
    )
    if corpus is None:
        raise NotFoundError(f"Corpus {corpus_id} not found.")
    count = await db.scalar(
        select(func.count(McpToken.id))
        .where(McpToken.corpus_id == corpus.id)
        .where(McpToken.revoked_at.is_(None))
    )
    return corpus, int(count or 0)


async def create_corpus(
    db: AsyncSession,
    *,
    name: str,
    description: str | None,
    collection_ids: list[uuid.UUID],
) -> tuple[Corpus, int]:
    """Insert a new corpus with the given (possibly empty) collection list."""
    name = name.strip()
    if not name:
        raise DomainValidationError("INVALID_NAME", "Corpus name cannot be empty.")

    corpus = Corpus(name=name, description=description)
    db.add(corpus)
    try:
        await db.flush()
    except IntegrityError as exc:
        await db.rollback()
        raise DomainValidationError(
            "DUPLICATE_NAME",
            f"A corpus named {name!r} already exists.",
        ) from exc

    if collection_ids:
        await _set_corpus_collections(db, corpus.id, collection_ids)
    await db.refresh(corpus, attribute_names=["collections"])
    return corpus, 0


async def update_corpus(
    db: AsyncSession,
    corpus_id: uuid.UUID,
    *,
    name: str | None,
    description: str | None,
    collection_ids: list[uuid.UUID] | None,
) -> tuple[Corpus, int]:
    """Patch any subset of fields. Pass ``collection_ids=[]`` to clear the M:N."""
    corpus, _ = await get_corpus(db, corpus_id)
    if name is not None:
        n = name.strip()
        if not n:
            raise DomainValidationError("INVALID_NAME", "Corpus name cannot be empty.")
        corpus.name = n
    if description is not None:
        corpus.description = description
    corpus.updated_at = datetime.now(UTC)
    if collection_ids is not None:
        await _set_corpus_collections(db, corpus.id, collection_ids)
    try:
        await db.flush()
    except IntegrityError as exc:
        await db.rollback()
        raise DomainValidationError(
            "DUPLICATE_NAME",
            f"A corpus with that name already exists.",
        ) from exc
    await db.refresh(corpus, attribute_names=["collections"])
    return await get_corpus(db, corpus.id)


async def delete_corpus(db: AsyncSession, corpus_id: uuid.UUID) -> None:
    """Drop a corpus. Cascade revokes every token issued for it."""
    corpus, _ = await get_corpus(db, corpus_id)
    await db.delete(corpus)
    await db.flush()


async def _set_corpus_collections(
    db: AsyncSession, corpus_id: uuid.UUID, collection_ids: list[uuid.UUID]
) -> None:
    """Replace the corpus's M:N rows wholesale with the given ids.

    Validates that every supplied id refers to an existing collection;
    silently drops duplicates.
    """
    unique_ids = list({c for c in collection_ids})
    if unique_ids:
        # Verify every id is a real collection — raises if any miss.
        rows = (
            await db.execute(
                select(Collection.id).where(Collection.id.in_(unique_ids))
            )
        ).scalars().all()
        missing = set(unique_ids) - set(rows)
        if missing:
            raise DomainValidationError(
                "UNKNOWN_COLLECTION",
                f"Unknown collection ids: {sorted(str(m) for m in missing)}",
            )

    from sqlalchemy import delete as sa_delete

    await db.execute(
        sa_delete(corpus_collections).where(
            corpus_collections.c.corpus_id == corpus_id
        )
    )
    if unique_ids:
        await db.execute(
            corpus_collections.insert(),
            [{"corpus_id": corpus_id, "collection_id": cid} for cid in unique_ids],
        )


# ── MCP token issuance / revocation / resolution ──────────────────────────────


async def list_tokens(
    db: AsyncSession, corpus_id: uuid.UUID
) -> list[McpToken]:
    """All tokens (active + revoked) for a corpus, newest first."""
    await get_corpus(db, corpus_id)  # 404 if missing
    return list(
        (
            await db.execute(
                select(McpToken)
                .where(McpToken.corpus_id == corpus_id)
                .order_by(McpToken.created_at.desc())
            )
        )
        .scalars()
        .all()
    )


async def issue_token(
    db: AsyncSession,
    *,
    corpus_id: uuid.UUID,
    label: str,
    actor: User,
    base_url: str,
) -> tuple[McpToken, str, str]:
    """Generate a new bearer token for *corpus_id*.

    Returns a 3-tuple ``(row, plaintext, claude_desktop_snippet)``. The
    plaintext is *never* persisted — only its bcrypt hash. The snippet
    is a copy-pasteable JSON config keyed at *base_url* so the admin
    can hand it to the editor as-is.
    """
    label = label.strip()
    if not label:
        raise DomainValidationError("INVALID_LABEL", "Token label cannot be empty.")
    await get_corpus(db, corpus_id)  # 404 if missing

    # 32-byte urlsafe → 43-char b64. Decoded length = 32 random bytes
    # of entropy, which is well above the practical lower bound for
    # bearer tokens. Prefix to make it self-identifying in logs / leaks.
    plaintext = "aracne2_mcp_" + secrets.token_urlsafe(32)
    row = McpToken(
        corpus_id=corpus_id,
        label=label,
        hashed_token=hash_password(plaintext),
        created_by=actor.id,
    )
    db.add(row)
    await db.flush()

    snippet = _format_claude_desktop_snippet(base_url=base_url, plaintext=plaintext)
    return row, plaintext, snippet


def _format_claude_desktop_snippet(*, base_url: str, plaintext: str) -> str:
    """Build a Claude Desktop ``mcpServers`` config block, ready to paste."""
    base_url = base_url.rstrip("/")
    return (
        "{\n"
        '  "mcpServers": {\n'
        '    "aracne2": {\n'
        f'      "url": "{base_url}/api/v1/mcp/sse",\n'
        '      "headers": {\n'
        f'        "Authorization": "Bearer {plaintext}"\n'
        "      }\n"
        "    }\n"
        "  }\n"
        "}"
    )


async def revoke_token(
    db: AsyncSession, corpus_id: uuid.UUID, token_id: uuid.UUID
) -> None:
    """Set ``revoked_at`` on a token. Idempotent — already-revoked tokens stay so."""
    row = await db.scalar(
        select(McpToken)
        .where(McpToken.id == token_id)
        .where(McpToken.corpus_id == corpus_id)
    )
    if row is None:
        raise NotFoundError(f"Token {token_id} not found in corpus {corpus_id}.")
    if row.revoked_at is None:
        row.revoked_at = datetime.now(UTC)
        await db.flush()


async def resolve_token(
    db: AsyncSession, plaintext: str
) -> tuple[McpToken, Corpus] | None:
    """Look up the (token, corpus) for the given plaintext, or None.

    The plaintext starts with the ``aracne2_mcp_`` self-identifying
    prefix; bearers that don't match it are rejected without touching
    the DB. For matching bearers we walk every non-revoked row and
    bcrypt-verify — the row count per corpus is small (a handful per
    deployment), so the linear scan is fine.

    Side effect: bumps ``last_used_at`` on the matched row.
    """
    if not plaintext.startswith("aracne2_mcp_"):
        return None
    rows = (
        await db.execute(
            select(McpToken).where(McpToken.revoked_at.is_(None))
        )
    ).scalars().all()
    for row in rows:
        if verify_password(plaintext, row.hashed_token):
            row.last_used_at = datetime.now(UTC)
            await db.flush()
            corpus = await db.scalar(
                select(Corpus)
                .where(Corpus.id == row.corpus_id)
                .options(selectinload(Corpus.collections))
            )
            if corpus is None:
                return None
            return row, corpus
    return None
